<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Note extends Model
{
    use HasUuids, SoftDeletes;

    protected $primaryKey = 'note_id';

    protected $touches = ['project'];

    /** UUID column automatically generated by HasUuids */
    public function uniqueIds(): array
    {
        return ['note_id'];
    }

    protected $fillable = [
        'project_id',
        'parent_note_id',
        'depth',
        'sort_order',
        'title',
        'body',
    ];

    protected function casts(): array
    {
        return [
            'depth' => 'integer',
            'sort_order' => 'integer',
        ];
    }

    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------

    /** Depth limit (0-based). Depth 2 = 3rd level = cannot have children */
    public const MAX_DEPTH = 2;

    /** Body character limit (matching TEXT in MySQL = 65,535, or MEDIUMTEXT = 16MB) */
    public const MAX_BODY_CHARS = 65535;

    // -----------------------------------------------------------------------
    // Relations
    // -----------------------------------------------------------------------

    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class, 'project_id', 'project_id');
    }

    public function parent(): BelongsTo
    {
        return $this->belongsTo(Note::class, 'parent_note_id', 'note_id');
    }

    /** Direct sub-tabs (1 level) */
    public function children(): HasMany
    {
        return $this->hasMany(Note::class, 'parent_note_id', 'note_id')
            ->orderBy('sort_order');
    }

    /** All descendants down to the deepest level (eager via nested) */
    public function childrenRecursive(): HasMany
    {
        return $this->children()->with('childrenRecursive');
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Is this note allowed to have sub-tabs? */
    public function canHaveChildren(): bool
    {
        return $this->depth < self::MAX_DEPTH;
    }

    /** Is this a root (top-level) note? */
    public function isRoot(): bool
    {
        return is_null($this->parent_note_id);
    }
}
